// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7GPfSY34y3sigedZ25aVaXAEhMQeOMNA',
    appId: '1:779208595057:web:27fc049ba377882393edd0',
    messagingSenderId: '779208595057',
    projectId: 'social-app-7a52f',
    authDomain: 'social-app-7a52f.firebaseapp.com',
    storageBucket: 'social-app-7a52f.appspot.com',
    measurementId: 'G-6Y1L3D9WYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpysVjWkFv2OOXe0bUke81H-dG56RvpCI',
    appId: '1:779208595057:android:bb1be9cf18a071d893edd0',
    messagingSenderId: '779208595057',
    projectId: 'social-app-7a52f',
    storageBucket: 'social-app-7a52f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvl2mm47sgajznUljmLksKIXv1d0GKCDw',
    appId: '1:779208595057:ios:eabe171d6344a9fe93edd0',
    messagingSenderId: '779208595057',
    projectId: 'social-app-7a52f',
    storageBucket: 'social-app-7a52f.appspot.com',
    androidClientId: '779208595057-nm8juiqubm7hc9bft7pfvgqj961pq5u7.apps.googleusercontent.com',
    iosClientId: '779208595057-0h84qh5q768g6cc2jjs3llpmoavk4j20.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvl2mm47sgajznUljmLksKIXv1d0GKCDw',
    appId: '1:779208595057:ios:eabe171d6344a9fe93edd0',
    messagingSenderId: '779208595057',
    projectId: 'social-app-7a52f',
    storageBucket: 'social-app-7a52f.appspot.com',
    androidClientId: '779208595057-nm8juiqubm7hc9bft7pfvgqj961pq5u7.apps.googleusercontent.com',
    iosClientId: '779208595057-0h84qh5q768g6cc2jjs3llpmoavk4j20.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialTest',
  );
}
